#Copyright (c) 2016 by Cisco Systems, Inc. All rights reserved.
# coding: utf-8

"""
    API Documentation

    Credential Management holds credentials for things and users.  Credential Management can import or create new credentials for a thing/user, authenticate credentials, reset credentials and delete credentials.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.io_t_exception_model import IoTExceptionModel
from .models.secret import Secret
from .models.thing_base_credential import ThingBaseCredential
from .models.thing_credential_response import ThingCredentialResponse
from .models.user_base_credential import UserBaseCredential
from .models.user_credential_response import UserCredentialResponse

# import apis into sdk package
from .apis.thing_credentials_api import ThingCredentialsApi
from .apis.user_credentials_api import UserCredentialsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
configuration.verify_ssl = False
