# coding: utf-8

"""
    API Documentation

    Credential Management holds credentials for things and users.  Credential Management can import or create new credentials for a thing/user, authenticate credentials, reset credentials and delete credentials.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ThingCredentialResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uid=None, thing_uid=None, credential_type=None, credential=None):
        """
        ThingCredentialResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'uid': 'str',
            'thing_uid': 'str',
            'credential_type': 'str',
            'credential': 'Secret'
        }

        self.attribute_map = {
            'uid': 'uid',
            'thing_uid': 'thingUid',
            'credential_type': 'credentialType',
            'credential': 'credential'
        }

        self._uid = uid
        self._thing_uid = thing_uid
        self._credential_type = credential_type
        self._credential = credential

    @property
    def uid(self):
        """
        Gets the uid of this ThingCredentialResponse.


        :return: The uid of this ThingCredentialResponse.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this ThingCredentialResponse.


        :param uid: The uid of this ThingCredentialResponse.
        :type: str
        """

        self._uid = uid

    @property
    def thing_uid(self):
        """
        Gets the thing_uid of this ThingCredentialResponse.


        :return: The thing_uid of this ThingCredentialResponse.
        :rtype: str
        """
        return self._thing_uid

    @thing_uid.setter
    def thing_uid(self, thing_uid):
        """
        Sets the thing_uid of this ThingCredentialResponse.


        :param thing_uid: The thing_uid of this ThingCredentialResponse.
        :type: str
        """

        self._thing_uid = thing_uid

    @property
    def credential_type(self):
        """
        Gets the credential_type of this ThingCredentialResponse.


        :return: The credential_type of this ThingCredentialResponse.
        :rtype: str
        """
        return self._credential_type

    @credential_type.setter
    def credential_type(self, credential_type):
        """
        Sets the credential_type of this ThingCredentialResponse.


        :param credential_type: The credential_type of this ThingCredentialResponse.
        :type: str
        """

        self._credential_type = credential_type

    @property
    def credential(self):
        """
        Gets the credential of this ThingCredentialResponse.


        :return: The credential of this ThingCredentialResponse.
        :rtype: Secret
        """
        return self._credential

    @credential.setter
    def credential(self, credential):
        """
        Sets the credential of this ThingCredentialResponse.


        :param credential: The credential of this ThingCredentialResponse.
        :type: Secret
        """

        self._credential = credential

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
