#Copyright (c) 2016 by Cisco Systems, Inc. All rights reserved.
# coding: utf-8

"""
    API Documentation

    Credential Management holds credentials for things and users.  Credential Management can import or create new credentials for a thing/user, authenticate credentials, reset credentials and delete credentials.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class UserBaseCredential(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uid=None, credential_type=None, user_uid=None, credential=None):
        """
        UserBaseCredential - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'uid': 'str',
            'credential_type': 'str',
            'user_uid': 'str',
            'credential': 'Secret'
        }

        self.attribute_map = {
            'uid': 'uid',
            'credential_type': 'credentialType',
            'user_uid': 'userUid',
            'credential': 'credential'
        }

        self._uid = uid
        self._credential_type = credential_type
        self._user_uid = user_uid
        self._credential = credential

    @property
    def uid(self):
        """
        Gets the uid of this UserBaseCredential.


        :return: The uid of this UserBaseCredential.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this UserBaseCredential.


        :param uid: The uid of this UserBaseCredential.
        :type: str
        """

        self._uid = uid

    @property
    def credential_type(self):
        """
        Gets the credential_type of this UserBaseCredential.


        :return: The credential_type of this UserBaseCredential.
        :rtype: str
        """
        return self._credential_type

    @credential_type.setter
    def credential_type(self, credential_type):
        """
        Sets the credential_type of this UserBaseCredential.


        :param credential_type: The credential_type of this UserBaseCredential.
        :type: str
        """
        allowed_values = ["secret"]
        if credential_type not in allowed_values:
            raise ValueError(
                "Invalid value for `credential_type`, must be one of {0}"
                .format(allowed_values)
            )

        self._credential_type = credential_type

    @property
    def user_uid(self):
        """
        Gets the user_uid of this UserBaseCredential.


        :return: The user_uid of this UserBaseCredential.
        :rtype: str
        """
        return self._user_uid

    @user_uid.setter
    def user_uid(self, user_uid):
        """
        Sets the user_uid of this UserBaseCredential.


        :param user_uid: The user_uid of this UserBaseCredential.
        :type: str
        """

        self._user_uid = user_uid

    @property
    def credential(self):
        """
        Gets the credential of this UserBaseCredential.


        :return: The credential of this UserBaseCredential.
        :rtype: Secret
        """
        return self._credential

    @credential.setter
    def credential(self, credential):
        """
        Sets the credential of this UserBaseCredential.


        :param credential: The credential of this UserBaseCredential.
        :type: Secret
        """

        self._credential = credential

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
