# coding: utf-8

"""
    API documentation for Things Registration

    APIs for Thing Registration

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.io_t_exception_model import IoTExceptionModel
from .models.registration_request import RegistrationRequest
from .models.registration_response import RegistrationResponse
from .models.secret import Secret
from .models.thing import Thing
from .models.thing_service import ThingService
from .models.unique_identifier import UniqueIdentifier

# import apis into sdk package
from .apis.registration_api import RegistrationApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
configuration.verify_ssl = False

