# coding: utf-8

"""
    API documentation for Things Registration

    APIs for Thing Registration

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class RegistrationRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, thing=None, service=None):
        """
        RegistrationRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'thing': 'Thing',
            'service': 'ThingService'
        }

        self.attribute_map = {
            'thing': 'thing',
            'service': 'service'
        }

        self._thing = thing
        self._service = service

    @property
    def thing(self):
        """
        Gets the thing of this RegistrationRequest.


        :return: The thing of this RegistrationRequest.
        :rtype: Thing
        """
        return self._thing

    @thing.setter
    def thing(self, thing):
        """
        Sets the thing of this RegistrationRequest.


        :param thing: The thing of this RegistrationRequest.
        :type: Thing
        """

        self._thing = thing

    @property
    def service(self):
        """
        Gets the service of this RegistrationRequest.


        :return: The service of this RegistrationRequest.
        :rtype: ThingService
        """
        return self._service

    @service.setter
    def service(self, service):
        """
        Sets the service of this RegistrationRequest.


        :param service: The service of this RegistrationRequest.
        :type: ThingService
        """

        self._service = service

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
