#Copyright (c) 2016 by Cisco Systems, Inc. All rights reserved.
# coding: utf-8

"""
    API documentation for User Service

    These are all the APIs for the User Service

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class UserPolicyUnit(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, allowed_permissions=None, resource_crns=None, conditions=None):
        """
        UserPolicyUnit - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'allowed_permissions': 'list[str]',
            'resource_crns': 'list[str]',
            'conditions': 'list[FilterCriteria]'
        }

        self.attribute_map = {
            'allowed_permissions': 'allowedPermissions',
            'resource_crns': 'resourceCrns',
            'conditions': 'conditions'
        }

        self._allowed_permissions = allowed_permissions
        self._resource_crns = resource_crns
        self._conditions = conditions

    @property
    def allowed_permissions(self):
        """
        Gets the allowed_permissions of this UserPolicyUnit.


        :return: The allowed_permissions of this UserPolicyUnit.
        :rtype: list[str]
        """
        return self._allowed_permissions

    @allowed_permissions.setter
    def allowed_permissions(self, allowed_permissions):
        """
        Sets the allowed_permissions of this UserPolicyUnit.


        :param allowed_permissions: The allowed_permissions of this UserPolicyUnit.
        :type: list[str]
        """

        self._allowed_permissions = allowed_permissions

    @property
    def resource_crns(self):
        """
        Gets the resource_crns of this UserPolicyUnit.


        :return: The resource_crns of this UserPolicyUnit.
        :rtype: list[str]
        """
        return self._resource_crns

    @resource_crns.setter
    def resource_crns(self, resource_crns):
        """
        Sets the resource_crns of this UserPolicyUnit.


        :param resource_crns: The resource_crns of this UserPolicyUnit.
        :type: list[str]
        """

        self._resource_crns = resource_crns

    @property
    def conditions(self):
        """
        Gets the conditions of this UserPolicyUnit.


        :return: The conditions of this UserPolicyUnit.
        :rtype: list[FilterCriteria]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """
        Sets the conditions of this UserPolicyUnit.


        :param conditions: The conditions of this UserPolicyUnit.
        :type: list[FilterCriteria]
        """

        self._conditions = conditions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
